package com.yrrlyb.aria.mobile.netease;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

/**
 * Golden vectors generated by the upstream Node implementation
 * (NeteaseCloudMusicApi 4.32 util/crypto.js + node-forge) with a FIXED
 * secret so every output byte is reproducible. Regeneration snippet lives in
 * NETEASE_API.md. If any assertion here fails after an edit to
 * NeteaseCrypto, the signing behaviour changed — stop and diff.
 */
public class NeteaseCryptoGoldenTest {
    private static final String SECRET = "pS2cXyQz1AvWmL5N";
    private static final String TEXT = "{\"foo\":\"bar\"}";

    @Test
    public void aesCbc_matchesNodeFirstLayer() {
        assertEquals("NGbW4wHjZGlAl2UoNs5AHQ==", NeteaseCrypto.aesCbcBase64(TEXT, "0CoJUm6Qyw8W8jud"));
    }

    @Test
    public void aesCbc_matchesNodeSecondLayer() {
        assertEquals("Zb+gO+1IwqX53l0G9lOuJNqCDFZRoBRaDJL9FwTDfnc=",
                NeteaseCrypto.aesCbcBase64("NGbW4wHjZGlAl2UoNs5AHQ==", SECRET));
    }

    @Test
    public void rsaNoPad_matchesForge() {
        assertEquals(
                "4408ebaf377f5b927592d898dd8d1dadc80198685efb06d6d99b169b367f8bee9305bd95ed74bc6f554c4ec205471807"
                        + "7ae6cb13fb309ac0d8a1391f11f9185426959a8b2c35aee44d059212cced51f77a9ceae7e9c574cdef672ad1b0b9a"
                        + "c4cfa1527ad7d45ae44f858c1791b53685d5fd07f9259038a9cd24a86f6e63e2663",
                NeteaseCrypto.rsaNoPadHex(new StringBuilder(SECRET).reverse().toString()));
    }

    @Test
    public void weapi_withFixedSecret_matchesNode() {
        NeteaseCrypto.WeapiParams params = NeteaseCrypto.weapiWithSecret(TEXT, SECRET);
        assertEquals("Zb+gO+1IwqX53l0G9lOuJNqCDFZRoBRaDJL9FwTDfnc=", params.params());
        assertEquals(
                "4408ebaf377f5b927592d898dd8d1dadc80198685efb06d6d99b169b367f8bee9305bd95ed74bc6f554c4ec205471807"
                        + "7ae6cb13fb309ac0d8a1391f11f9185426959a8b2c35aee44d059212cced51f77a9ceae7e9c574cdef672ad1b0b9a"
                        + "c4cfa1527ad7d45ae44f858c1791b53685d5fd07f9259038a9cd24a86f6e63e2663",
                params.encSecKey());
    }

    @Test
    public void weapi_secondVector_matchesNode() {
        NeteaseCrypto.WeapiParams params = NeteaseCrypto.weapiWithSecret("test", SECRET);
        assertEquals("pELklmfurqD8FiOJ4lSxSU0Ww9Ldvav/s7jQyAbts6M=", params.params());
    }

    @Test
    public void linuxapi_matchesNode() {
        assertEquals("53A9A2A125607D7CDE95D152E8D90E4D", NeteaseCrypto.linuxapi(TEXT).eparams());
    }

    @Test
    public void rsa_output_always_keyLength_even_when_highBitSet() {
        // Random secrets whose RSA result has the top bit set used to crash
        // with ArrayIndexOutOfBounds (129 bytes into a 128-byte buffer).
        String base62 = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        java.util.Random random = new java.util.Random(42);
        for (int i = 0; i < 200; i++) {
            StringBuilder secret = new StringBuilder(16);
            for (int j = 0; j < 16; j++) secret.append(base62.charAt(random.nextInt(62)));
            String hex = NeteaseCrypto.rsaNoPadHex(new StringBuilder(secret).reverse().toString());
            assertEquals("secret " + secret + " produced " + hex.length() + " chars", 256, hex.length());
        }
    }

    @Test
    public void eapi_matchesNode() {
        String url = "/api/v1/album";
        NeteaseCrypto.EapiParams params = NeteaseCrypto.eapi(url, TEXT);
        assertEquals(
                "D42E697C88A01B26648F1C5CBD2F9CA564C2E0E8044059F122256A9313B03B4FD66ED29C2BA141C01A2E4B0BA8C44B8ABA04616E54BA0C3F5CB6552F3ABC2D8ECF674605BEC20CEDED49DAD8072BA7E7B5D1909F42B1B5E28EFACB382D2E0744",
                params.params());
    }
}
